"use client";
import { useEffect, useState } from "react";
import {
  X,
  Lock,
  ShieldAlert,
  MapPin,
  QrCode,
  Sparkles,
  UserCheck,
  Compass,
  Coins,
  Clock,
  Calendar,
  AlertTriangle,
  ChevronDown,
  ExternalLink,
  ShieldCheck,
  Eye,
  HelpCircle,
  Info,
  Users,
  Zap,
  CheckCircle2,
  Share2,
  Layers,
  ArrowRight,
} from "lucide-react";
import ProfileCard from "./ProfileCard";
import ContractTimeline from "./ContractTimeline";
import { protocolNotes, hoursLabel, type ListingContract } from "@/lib/contract";
import { trustTier } from "./AppChrome";
import { useToast } from "./Feedback";
import { format, formatDistanceToNow } from "date-fns";

export function getListingMeta(kind: string, contract?: any, borrowMode?: string) {
  if (kind === "bounty_geo") {
    return {
      type: "bounty_geo",
      isBounty: true,
      label: "GPS Check-In",
      subtitle: "Physical Geofence Verification",
      Icon: MapPin,
      badgeColor: "text-[var(--gold)]",
      badgeBg: "bg-[var(--gold)]/10 border-[var(--gold)]/30",
      accentBorder: "border-[var(--gold)]",
      oracleName: "GPS Sensor Geofence",
      oracleExplanation:
        "Acta reads the challenger's authenticated mobile device GPS coordinates to verify physical presence within the designated target perimeter.",
      howItVerifies:
        "Acta reads the device's authenticated GPS sensor coordinates. Once your location confirms within the allowed radius, the smart contract vault triggers the payout immediately. If presence check is enabled, a live camera photo of the scene is also inspected.",
      mustDo:
        "Physically travel to the target coordinates, open Acta, grant location permissions, and tap 'Verify GPS Check-In' while inside the perimeter.",
    };
  }
  if (kind === "bounty_qr") {
    return {
      type: "bounty_qr",
      isBounty: true,
      label: "ScanQuest Token",
      subtitle: "Cryptographic Geocache Scan",
      Icon: QrCode,
      badgeColor: "text-[var(--gold)]",
      badgeBg: "bg-[var(--gold)]/10 border-[var(--gold)]/30",
      accentBorder: "border-[var(--gold)]",
      oracleName: "Signed Cryptographic QR",
      oracleExplanation:
        "A physical QR code containing a single-use Ed25519 signature generated by the sponsor is placed at the designated location. Scanning it with Acta's in-app camera verifies the cryptographic signature on-chain.",
      howItVerifies:
        "The sponsor pre-signs a single-use cryptographic token. Scanning the physical code mathematically proves your physical presence at the location and claims the locked reward instantly. It is mathematically non-forgeable and immune to GPS spoofing.",
      mustDo:
        "Locate the hidden physical QR token at the target site and scan it using Acta's in-app camera scanner.",
    };
  }
  if (kind === "bounty_manual") {
    return {
      type: "bounty_manual",
      isBounty: true,
      label: "In-Person Verification",
      subtitle: "Sponsor Manual Sign-Off",
      Icon: UserCheck,
      badgeColor: "text-[var(--gold)]",
      badgeBg: "bg-[var(--gold)]/10 border-[var(--gold)]/30",
      accentBorder: "border-[var(--gold)]",
      oracleName: "Sponsor Direct Approval",
      oracleExplanation:
        "The sponsor inspects proof of completion directly or verifies you in person, then signs an on-chain authorization in Nimiq Pay to release the escrow.",
      howItVerifies:
        "After you submit evidence or meet the sponsor, the sponsor reviews the submission in their Acta inbox and cryptographically signs approval from their wallet, triggering immediate vault payout.",
      mustDo:
        "Complete the specified task, coordinate with the sponsor in person or via inbox, and obtain the sponsor's cryptographic sign-off.",
    };
  }
  if (kind === "bounty_venture") {
    return {
      type: "bounty_venture",
      isBounty: true,
      label: "Online Venture",
      subtitle: "Milestone & Digital Review",
      Icon: Compass,
      badgeColor: "text-[var(--gold)]",
      badgeBg: "bg-[var(--gold)]/10 border-[var(--gold)]/30",
      accentBorder: "border-[var(--gold)]",
      oracleName: "AI-Assisted Milestone Review",
      oracleExplanation:
        "Challengers submit deliverables, code repositories, or campaign proof. Gemini AI pre-screens the submission for completeness, then the sponsor executes final milestone release.",
      howItVerifies:
        "Submissions are evaluated by AI for relevance and adherence to criteria, then presented to the sponsor with an AI recommendation. Sponsor signs off to release bounty.",
      mustDo:
        "Produce the requested digital deliverable or milestone, enter the submission details and proof links in your Contracts tab, and await the sponsor's review.",
    };
  }
  if (kind === "borrow") {
    const isRent = borrowMode === "rent";
    return {
      type: "borrow",
      isBounty: false,
      label: isRent ? "Rental Request" : "Equipment Loan",
      subtitle: isRent ? "Requester Collateral Vault" : "Collateralized Escrow Covenant",
      Icon: Lock,
      badgeColor: "text-[var(--sky)]",
      badgeBg: "bg-[var(--sky)]/10 border-[var(--sky)]/30",
      accentBorder: "border-[var(--sky)]",
      oracleName: "Mutual Return QR Protocol",
      oracleExplanation: isRent
        ? "Requester has pre-funded and locked collateral into the vault upon listing. When the gear is returned, you scan the borrower's Return QR to release 100% of collateral back to them."
        : "Borrower locks collateral into the vault upon rental acceptance. Upon physical return of the item, lender scans borrower's one-time cryptographic Return QR to release 100% of collateral.",
      howItVerifies:
        "Collateral is held safely in the autonomous smart vault during the loan. Upon returning the asset, borrower displays their Return Code; lender scans it with Acta to trigger immediate collateral refund.",
      mustDo: isRent
        ? "Accept request, arrange equipment handoff with requester, inspect item upon return, and scan borrower's Return QR code."
        : "Lock the collateral deposit in the vault, coordinate pickup with the lender, use the asset responsibly, and present your Return QR code upon returning the asset.",
    };
  }
  // Default bounty (vision)
  return {
    type: "bounty",
    isBounty: true,
    label: "Vision Oracle",
    subtitle: "Multimodal AI Photo Verification",
    Icon: Sparkles,
    badgeColor: "text-[var(--gold)]",
    badgeBg: "bg-[var(--gold)]/10 border-[var(--gold)]/30",
    accentBorder: "border-[var(--gold)]",
    oracleName: "Multimodal Gemini Vision AI",
    oracleExplanation:
      "Google Gemini Multimodal Vision AI evaluates your high-resolution proof photo directly against the sponsor's criteria prompt.",
    howItVerifies:
      "When you upload a scene photo, Gemini Vision inspects the image for criteria compliance, scene realism, and absence of digital forgery. If valid, the protocol triggers automatic vault payout in seconds.",
    mustDo:
      "Perform the required task according to the criteria. Take a clear photo of the completed proof and submit it through Acta for AI inspection.",
  };
}

function CountdownTimer({ expiresAt }: { expiresAt: number | null }) {
  const [timeLeft, setTimeLeft] = useState<{
    days: number;
    hours: number;
    mins: number;
    secs: number;
    isExpired: boolean;
  } | null>(null);

  useEffect(() => {
    if (!expiresAt) {
      setTimeLeft(null);
      return;
    }
    function update() {
      const diff = Number(expiresAt) - Date.now();
      if (diff <= 0) {
        setTimeLeft({ days: 0, hours: 0, mins: 0, secs: 0, isExpired: true });
        return;
      }
      const days = Math.floor(diff / (1000 * 60 * 60 * 24));
      const hours = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      const mins = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
      const secs = Math.floor((diff % (1000 * 60)) / 1000);
      setTimeLeft({ days, hours, mins, secs, isExpired: false });
    }
    update();
    const timer = setInterval(update, 1000);
    return () => clearInterval(timer);
  }, [expiresAt]);

  if (!expiresAt) {
    return (
      <div className="flex items-center gap-1.5 text-[11px] text-[var(--ink3)]">
        <Clock size={12} className="text-[var(--ink3)]" />
        <span>Indefinite duration (No expiry)</span>
      </div>
    );
  }

  if (!timeLeft) return null;

  if (timeLeft.isExpired) {
    return (
      <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-[var(--wax)]/15 border border-[var(--wax)]/40 text-[var(--wax)] text-[11px] font-bold">
        <AlertTriangle size={12} />
        <span>Listing Expired</span>
      </div>
    );
  }

  return (
    <div className="flex items-center gap-2 px-2.5 py-1 rounded-xl bg-[var(--surface2)] border border-[var(--line)]/25 text-[11px]">
      <Clock size={12} className="text-[var(--gold)] animate-pulse" />
      <span className="text-[var(--ink3)]">Closes in:</span>
      <span className="font-mono font-bold text-[var(--ink)] tnum">
        {timeLeft.days > 0 && `${timeLeft.days}d `}
        {String(timeLeft.hours).padStart(2, "0")}h {String(timeLeft.mins).padStart(2, "0")}m {String(timeLeft.secs).padStart(2, "0")}s
      </span>
    </div>
  );
}

function OwnerControls({
  listingId,
  hasLocks,
  activeCount,
  listingKind,
  amountNIM,
  listingTitle,
  onDone,
  onShowQr,
}: {
  listingId: string;
  hasLocks: boolean;
  activeCount: number;
  listingKind: string;
  amountNIM: number;
  listingTitle: string;
  onDone: () => void;
  onShowQr?: (token: string, escrow: any) => void;
}) {
  const toast = useToast();
  const [busy, setBusy] = useState(false);
  const [qrBusy, setQrBusy] = useState(false);

  async function act(mode?: "close") {
    setBusy(true);
    try {
      const res = await fetch("/api/cancel", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ type: "listing", id: listingId, ...(mode ? { mode } : {}) }),
      });
      const d = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error((d as any).error || "Action failed");
      toast({
        type: "success",
        title: mode === "close" ? "Listing closed to new accepts" : "Listing cancelled & fully refunded",
        body:
          mode === "close"
            ? "Active participants can finish their work, but no new participants may accept."
            : `${amountNIM.toLocaleString()} NIM refunded from vault to your wallet.`,
      });
      onDone();
    } catch (e) {
      toast({ type: "error", title: e instanceof Error ? e.message : "Action failed" });
    } finally {
      setBusy(false);
    }
  }

  async function generateQr() {
    setQrBusy(true);
    try {
      const res = await fetch("/api/qr/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: "scan_quest",
          escrowId: listingId,
          amount: amountNIM,
          chain: "nimiq-testnet",
        }),
      });
      const d = await res.json();
      if (!res.ok) throw new Error(d.error || "Failed to generate QR");
      if (onShowQr) {
        onShowQr(d.token, { title: listingTitle, amountNIM });
      } else {
        toast({ type: "success", title: "ScanQuest QR Generated", body: "Token generated successfully." });
      }
    } catch (e) {
      toast({ type: "error", title: e instanceof Error ? e.message : "QR generation failed" });
    } finally {
      setQrBusy(false);
    }
  }

  return (
    <div className="space-y-3 mt-4">
      {listingKind === "bounty_qr" && (
        <button
          onClick={generateQr}
          disabled={qrBusy}
          className="w-full py-2.5 px-4 rounded-xl font-bold text-xs flex items-center justify-center gap-2 bg-gradient-to-r from-[var(--sky)] to-[var(--sky)]/80 text-[#181206] shadow-sm btn-press disabled:opacity-50"
        >
          <QrCode size={14} />
          <span>{qrBusy ? "Generating QR…" : "Generate / Show ScanQuest QR Token"}</span>
        </button>
      )}

      {hasLocks ? (
        <div className="space-y-2">
          <div className="rounded-xl bg-[var(--gold)]/10 border border-[var(--gold)]/25 p-3 text-[11.5px] leading-relaxed text-[var(--ink2)]">
            <span className="font-bold text-[var(--gold)] block mb-1">Active Lock Protection</span>
            {activeCount} participant(s) currently hold active locks. To protect in-progress work, smart contract rules require active locks to finish or expire before full cancellation. You may close the listing to new accepts at any time.
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => act("close")}
              disabled={busy}
              className="flex-1 rounded-xl py-2.5 px-3 bg-[var(--gold)]/15 hover:bg-[var(--gold)]/25 border border-[var(--gold)]/40 text-[12px] font-bold text-[var(--gold)] disabled:opacity-50 transition-all btn-press"
            >
              {busy ? "Closing…" : "Close to New Accepts"}
            </button>
            <button
              disabled
              title="Active locks must finish before full cancellation and deposit refund"
              className="flex-1 rounded-xl py-2.5 px-3 border border-[var(--line)]/15 text-[11px] font-medium text-[var(--ink3)] opacity-40 cursor-not-allowed"
            >
              Cancel (Active Locks Held)
            </button>
          </div>
        </div>
      ) : (
        <div className="space-y-2">
          <div className="rounded-xl bg-[color-mix(in_srgb,var(--ink)_5%,transparent)] border border-[var(--line)]/20 p-2.5 text-[11px] text-[var(--ink3)]">
            No active locks held. You can pause accepts or cancel for an immediate 100% full vault refund ({amountNIM.toLocaleString()} NIM).
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => act("close")}
              disabled={busy}
              className="flex-1 rounded-xl py-2.5 px-3 bg-[var(--surface2)] hover:bg-[var(--line)]/10 border border-[var(--line)]/30 text-[12px] font-semibold text-[var(--ink)] disabled:opacity-50 transition-all btn-press"
            >
              {busy ? "Closing…" : "Close to New Accepts"}
            </button>
            <button
              onClick={() => act()}
              disabled={busy}
              className="flex-1 rounded-xl py-2.5 px-3 bg-[var(--wax)]/15 hover:bg-[var(--wax)]/25 border border-[var(--wax)]/40 text-[12px] font-bold text-[var(--wax)] disabled:opacity-50 transition-all btn-press"
            >
              {busy ? "Cancelling…" : "Cancel & Full Refund"}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function ProtocolDossier({
  listing,
  contract,
  meta,
  isOwner,
}: {
  listing: any;
  contract: ListingContract | null;
  meta: ReturnType<typeof getListingMeta>;
  isOwner: boolean;
}) {
  const [isOpen, setIsOpen] = useState(false);

  const durationLabel = listing.durationDays ? `${listing.durationDays} days` : "1 day";
  const deadlineHours = contract?.deadlineHours || 72;
  const isRentRequest = listing.kind === "borrow" && listing.borrowMode === "rent";

  const faqs = [
    {
      q: "What happens next if I accept?",
      a: meta.isBounty
        ? `Your Nimiq address is enrolled as an active challenger for this bounty. Your personal countdown timer (${deadlineHours} hours) begins. The prize reward (${listing.collateralNIM.toLocaleString()} NIM) remains safely locked in the protocol's autonomous smart vault. The listing remains open until the first valid submission is completed and verified.`
        : isRentRequest
        ? `You accept the requester's call to provide equipment. Since the requester already locked ${listing.collateralNIM.toLocaleString()} NIM collateral into the autonomous smart vault upon posting, you deposit 0 NIM. You coordinate asset handoff and inspect the gear upon return.`
        : `Your collateral deposit (${listing.collateralNIM.toLocaleString()} NIM) is locked into the protocol's autonomous escrow vault. The lender is alerted to prepare the equipment and arrange handover. Your rental covenant period (${durationLabel}) begins upon handover.`,
    },
    {
      q: "What would I have to do?",
      a: meta.mustDo,
    },
    {
      q: "What does the platform or system do?",
      a: "Acta is a decentralized protocol running non-custodial smart escrow on the Nimiq blockchain. The platform never takes custody of funds, cannot seize deposits, and cannot arbitrarily freeze user balances. All settlements and refunds are executed programmatically through autonomous smart contracts.",
    },
    {
      q: "What does the counterparty (sponsor/lender/requester) do?",
      a: meta.isBounty
        ? "The sponsor has already funded 100% of the prize upfront into the escrow vault. For automated oracles (Vision, GPS, QR), the sponsor has no ability to withhold payout once your proof validates. For manual review contracts, the sponsor must review submissions within 48 hours or the contract triggers automatic review escalation."
        : isRentRequest
        ? "The requester has already locked 100% of the collateral into the smart vault upfront. When they return your asset in good order, you scan their Return QR code to unlock and return their collateral."
        : "The lender provides the listed asset. Upon receiving the asset back in satisfactory condition, the lender scans your dynamic Return QR code, triggering an instant release of your collateral back to your wallet.",
    },
    {
      q: "What can third parties or oracles do?",
      a: "Oracles (multimodal AI models, GPS distance algorithms, cryptographic verifiers) only have permission to evaluate whether submitted proof satisfies the contract criteria. They have zero custody of funds and cannot divert payouts to any third party. If proof passes, the smart vault releases payout immediately. If proof fails, your balance is never touched.",
    },
    {
      q: "Who has access and who can see it?",
      a: "This listing is publicly discoverable on the Acta Radar feed. All participants, settlement transactions, and proofs are recorded transparently on the public Nimiq blockchain. No real-world KYC or personal identity is required—only your cryptographic Nimiq address.",
    },
    {
      q: "How many people can participate?",
      a: meta.isBounty
        ? "Standard bounties are winner-takes-all: the first verified submission to pass the oracle wins the bounty and concludes the listing. Active challengers can work on the task simultaneously until a valid proof is settled."
        : "Exclusive 1-on-1 rental. Only one counterparty holds the asset during the covenant period.",
    },
    {
      q: "How will I be charged or will I be charged anything and why?",
      a: meta.isBounty
        ? "ZERO CHARGES FOR CHALLENGERS. Joining, accepting, and submitting proofs is 100% FREE. You never lock collateral, and failing a check costs 0 NIM. When you win, the vault transfers the reward to you minus the standard 0.0011 NIM protocol settlement & network gas fee."
        : isRentRequest
        ? "0 NIM CHARGED TO ACCEPT. As the provider supplying gear to a requester whose collateral is already securely held in the protocol vault, you do not deposit collateral. When the gear is returned and you scan the Return QR, settlement is executed without deducting your funds."
        : "You lock the required collateral into escrow. When you return the asset, 100% of your collateral is unlocked and returned to you, minus the minimal 0.0011 NIM settlement/network fee.",
    },
  ];

  return (
    <div className="mt-5 rounded-2xl border border-[var(--line)]/25 bg-[var(--surface)] overflow-hidden transition-all">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between p-3.5 hover:bg-[color-mix(in_srgb,var(--gold)_4%,transparent)] transition-colors text-left"
      >
        <div className="flex items-center gap-2.5">
          <div className="w-7 h-7 rounded-xl bg-[var(--gold)]/10 flex items-center justify-center text-[var(--gold)]">
            <HelpCircle size={15} />
          </div>
          <div>
            <p className="text-[12.5px] font-bold text-[var(--ink)]">Protocol Covenant & Operational Terms</p>
            <p className="text-[10px] text-[var(--ink3)]">Full breakdown: what happens next, oracles, rules & fees</p>
          </div>
        </div>
        <div className="flex items-center gap-1.5 text-[11px] font-semibold text-[var(--gold)] shrink-0">
          <span>{isOpen ? "Collapse" : "Read Terms"}</span>
          <ChevronDown
            size={15}
            className={`transition-transform duration-200 ${isOpen ? "rotate-180" : ""}`}
          />
        </div>
      </button>

      {isOpen && (
        <div className="border-t border-[var(--line)]/20 p-3.5 space-y-3.5 bg-[var(--surface2)]/40 animate-fade-in text-[12px]">
          <div className="rounded-xl bg-[var(--gold)]/10 border border-[var(--gold)]/20 p-2.5 text-[11px] text-[var(--gold2)] flex items-center gap-2">
            <ShieldCheck size={14} className="shrink-0 text-[var(--gold)]" />
            <span>Autonomous Smart Vault Guarantee: Non-custodial, peer-to-peer, verified on Nimiq.</span>
          </div>

          {faqs.map((f, i) => (
            <div key={i} className="space-y-1">
              <h4 className="font-bold text-[var(--ink)] flex items-center gap-1.5 text-[11.5px]">
                <span className="w-1.5 h-1.5 rounded-full bg-[var(--gold)] shrink-0" />
                {f.q}
              </h4>
              <p className="text-[11px] leading-relaxed text-[var(--ink2)] pl-3">
                {f.a}
              </p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

const REPORT_REASONS = [
  ["scam", "Scam or fraud"],
  ["unfunded", "Reward not actually locked"],
  ["abusive", "Abusive content"],
  ["miscategorized", "Wrong type / misleading"],
  ["other", "Something else"],
] as const;

function ReportControl({ listingId, isOwner }: { listingId: string; isOwner: boolean }) {
  const toast = useToast();
  const [count, setCount] = useState(0);
  const [mine, setMine] = useState<string | null>(null);
  const [breakdown, setBreakdown] = useState<Record<string, number>>({});
  const [reason, setReason] = useState<string>("scam");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    fetch(`/api/reports?listingId=${listingId}`)
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => {
        if (d) {
          setCount(Number(d.count ?? 0));
          setMine((d.mine as string) ?? null);
          setBreakdown((d.breakdown ?? {}) as Record<string, number>);
        }
      })
      .catch(() => {});
  }, [listingId]);

  async function submit() {
    setBusy(true);
    try {
      const res = await fetch("/api/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ listingId, reason }),
      });
      const d = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error((d as any).error || "Report failed");
      setMine(reason);
      setCount((c) => (mine ? c : c + 1));
      toast({ type: "success", title: "Reported for review", body: "Reputation, not deletion: the record stands while this is reviewed." });
    } catch (e) {
      toast({ type: "error", title: e instanceof Error ? e.message : "Report failed" });
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="mt-4 flex items-center gap-2">
      {mine ? (
        <p className="marginalia text-[11px]">You flagged this ({mine}) — thanks, it is in the review queue.</p>
      ) : (
        <>
          <select
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            className="flex-1 rounded-xl border border-[var(--line)] bg-transparent px-2.5 py-2 text-[11.5px] text-[var(--ink2)]"
          >
            {REPORT_REASONS.map(([v, label]) => (
              <option key={v} value={v}>
                {label}
              </option>
            ))}
          </select>
          <button
            onClick={submit}
            disabled={busy}
            className="ghost rounded-xl px-3.5 py-2 text-[11.5px] disabled:opacity-50"
          >
            {busy ? "Flagging…" : "Flag"}
          </button>
        </>
      )}
      {isOwner && count > 0 && (
        <span
          className="chip flex-none"
          style={{ color: "var(--wax)", borderColor: "color-mix(in srgb, var(--wax) 40%, transparent)" }}
          title={Object.entries(breakdown).map(([k, v]) => `${k} ×${v}`).join(", ")}
        >
          {count} report{count === 1 ? "" : "s"}
          {Object.keys(breakdown).length > 0 ? `: ${Object.entries(breakdown).map(([k, v]) => `${k}×${v}`).join(" ")}` : ""}
        </span>
      )}
    </div>
  );
}

export default function ListingDetailSheet({
  listingId,
  viewerTrust = 0,
  onAccept,
  onClose,
  onShowQr,
}: {
  listingId: string | null;
  viewerTrust?: number;
  onAccept: (l: any) => void;
  onClose: () => void;
  onShowQr?: (token: string, escrow: any) => void;
}) {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!listingId) return;
    setLoading(true);
    setData(null);
    fetch(`/api/listings/${listingId}`)
      .then((r) => (r.ok ? r.json() : null))
      .then(setData)
      .catch(() => setData(null))
      .finally(() => setLoading(false));
  }, [listingId]);

  if (!listingId) return null;
  const l = data?.listing;
  const contract: ListingContract | null = l?.contract ?? null;
  const notes = l ? protocolNotes(l, contract) : [];
  const lockedOut = Boolean(contract && contract.minTrust > viewerTrust && !data?.viewer?.isOwner);

  const meta = l ? getListingMeta(l.kind, contract, l.borrowMode) : getListingMeta("bounty");
  const createdDateStr = l?.createdAt ? format(new Date(Number(l.createdAt)), "PPp") : null;
  const createdRelStr = l?.createdAt ? formatDistanceToNow(new Date(Number(l.createdAt)), { addSuffix: true }) : null;
  const expiresDateStr = l?.expiresAt ? format(new Date(Number(l.expiresAt)), "PPp") : null;
  const hasLocation = Boolean(l?.requireLocation || contract?.geo || (l?.targetLat != null && l?.targetLng != null));
  const targetLat = l?.targetLat ?? contract?.geo?.lat;
  const targetLng = l?.targetLng ?? contract?.geo?.lng;
  const radiusM = contract?.geo?.radiusM || 50;

  return (
    <div
      className="fixed inset-0 z-[150] flex items-end justify-center bg-black/80 backdrop-blur-sm animate-fade-in sm:items-center"
      onClick={onClose}
    >
      <div
        className="floaty flex max-h-[90dvh] w-full max-w-[500px] flex-col rounded-t-3xl animate-slide-up sm:rounded-3xl overflow-hidden shadow-2xl border border-[var(--line)]/40"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header Bar */}
        <div className="flex items-center justify-between border-b border-[var(--line)]/20 p-4 bg-[var(--surface)]">
          <div className="flex items-center gap-2">
            <div className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[10px] font-extrabold tracking-wider uppercase ${meta.badgeBg} ${meta.badgeColor}`}>
              <meta.Icon size={12} />
              <span>{meta.label}</span>
            </div>
            {data?.viewer?.isOwner && (
              <span className="caps text-[8.5px] font-extrabold tracking-wider text-[var(--gold)] bg-[var(--gold)]/15 px-2 py-0.5 rounded-full border border-[var(--gold)]/30">
                Your Listing
              </span>
            )}
            {data?.viewer?.escrow && (
              <span className="caps text-[8.5px] font-extrabold tracking-wider text-[var(--sky)] bg-[var(--sky)]/15 px-2 py-0.5 rounded-full border border-[var(--sky)]/30">
                Accepted · Active
              </span>
            )}
          </div>
          <button onClick={onClose} className="ghost rounded-full p-1.5 text-[var(--ink3)] hover:text-[var(--ink)]">
            <X size={16} />
          </button>
        </div>

        {/* Scrollable Body */}
        <div className="flex-1 overflow-y-auto p-4 custom-parchment-scrollbar space-y-4">
          {loading || !l ? (
            <div className="space-y-3 py-2">
              <div className="skeleton h-8 w-3/4 rounded-xl" />
              <div className="skeleton h-28 rounded-2xl" />
              <div className="skeleton h-44 rounded-2xl" />
              <div className="skeleton h-32 rounded-2xl" />
            </div>
          ) : (
            <>
              {/* Title & Subhead */}
              <div>
                <h2 className="font-serif text-xl font-bold leading-tight text-[var(--ink)]">
                  {l.title}
                </h2>
                <p className="text-[11px] text-[var(--ink3)] mt-0.5">{meta.subtitle}</p>
              </div>

              {/* Financial Box by Role */}
              <div
                className={`rounded-2xl p-4 border shadow-sm ${
                  meta.isBounty
                    ? "bg-gradient-to-br from-[var(--gold)]/15 via-[var(--surface)] to-[color-mix(in_srgb,var(--gold)_8%,transparent)] border-[var(--gold)]/40"
                    : "bg-gradient-to-br from-[var(--sky)]/15 via-[var(--surface)] to-[color-mix(in_srgb,var(--sky)_8%,transparent)] border-[var(--sky)]/40"
                }`}
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <span className="caps text-[8px] font-extrabold tracking-wider text-[var(--ink3)]">
                      {meta.isBounty ? "Bounty Prize (Pre-funded in Vault)" : "Required Collateral Deposit"}
                    </span>
                    <div className="flex items-baseline gap-1.5 mt-0.5">
                      <span className="font-mono text-2xl font-black text-[var(--ink)] tnum">
                        {l.collateralNIM.toLocaleString()}
                      </span>
                      <span className={`text-xs font-bold ${meta.isBounty ? "text-[var(--gold)]" : "text-[var(--sky)]"}`}>
                        NIM
                      </span>
                    </div>
                  </div>

                  <div className="text-right">
                    <div className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-[var(--verdigris)]/15 border border-[var(--verdigris)]/30 text-[9px] font-bold text-[var(--verdigris)]">
                      <span className="w-1.5 h-1.5 rounded-full bg-[var(--verdigris)] animate-pulse" />
                      <span>{meta.isBounty ? "Funded on-chain" : "Escrowed loan"}</span>
                    </div>
                    {l.yieldNIM > 0 && (
                      <p className="text-[10px] text-[var(--verdigris)] font-semibold mt-1">
                        +{l.yieldNIM} NIM lender yield
                      </p>
                    )}
                  </div>
                </div>

                <div className="mt-2.5 pt-2.5 border-t border-[var(--line)]/15 flex items-center justify-between text-[11px] text-[var(--ink2)]">
                  <span>{meta.isBounty ? "Cost for you to accept:" : "Refundable on return:"}</span>
                  <span className="font-bold text-[var(--ink)]">
                    {meta.isBounty ? "0 NIM (Completely free)" : "100% (minus 0.0011 NIM network fee)"}
                  </span>
                </div>
              </div>

              {/* Timing, Creation & Countdown Grid */}
              <div className="rounded-2xl border border-[var(--line)]/25 bg-[var(--surface2)]/50 p-3.5 space-y-2.5">
                <div className="flex items-center justify-between">
                  <span className="caps text-[8px] font-extrabold tracking-wider text-[var(--ink3)]">Schedule & Validity</span>
                  <CountdownTimer expiresAt={l.expiresAt} />
                </div>

                <div className="grid grid-cols-2 gap-2 text-[11px]">
                  <div className="p-2 rounded-xl bg-[var(--surface)] border border-[var(--line)]/15">
                    <span className="caps text-[7.5px] text-[var(--ink3)] block mb-0.5">Date Created</span>
                    <span className="font-semibold text-[var(--ink)]">{createdDateStr || "—"}</span>
                    {createdRelStr && <p className="text-[9.5px] text-[var(--ink3)] mt-0.5">{createdRelStr}</p>}
                  </div>

                  <div className="p-2 rounded-xl bg-[var(--surface)] border border-[var(--line)]/15">
                    <span className="caps text-[7.5px] text-[var(--ink3)] block mb-0.5">Expires On</span>
                    <span className="font-semibold text-[var(--ink)]">{expiresDateStr || "Indefinite"}</span>
                    <p className="text-[9.5px] text-[var(--ink3)] mt-0.5">
                      {contract?.deadlineHours ? `${hoursLabel(contract.deadlineHours)} window once accepted` : "Valid until claimed"}
                    </p>
                  </div>
                </div>
              </div>

              {/* Sponsor Profile */}
              <div>
                <p className="caps mb-2 text-[8px] text-[var(--ink3)] font-bold tracking-wider">The Sponsor / Creator</p>
                <ProfileCard {...data.sponsor} />
              </div>

              {/* Requirements & Criteria */}
              <div className="rounded-2xl border border-[var(--line)]/25 bg-[var(--surface)] p-3.5 space-y-3">
                <div className="flex items-center gap-1.5">
                  <Sparkles size={14} className="text-[var(--gold)]" />
                  <h3 className="text-[12px] font-bold uppercase tracking-wider text-[var(--ink)]">
                    Proof Criteria & Instructions
                  </h3>
                </div>

                {contract?.criteria ? (
                  <div>
                    <span className="caps text-[8px] text-[var(--gold)] font-bold block mb-1">
                      Writ of Criteria (Must-Do):
                    </span>
                    <blockquote className="font-serif rounded-xl border-l-2 border-[var(--gold)] bg-[color-mix(in_srgb,var(--gold)_6%,transparent)] p-3 text-[13px] italic leading-relaxed text-[var(--ink)]">
                      “{contract.criteria}”
                    </blockquote>
                  </div>
                ) : null}

                {l.description ? (
                  <div>
                    <span className="caps text-[8px] text-[var(--ink3)] font-bold block mb-1">
                      Sponsor Notes & Description:
                    </span>
                    <p className="text-[12px] leading-relaxed text-[var(--ink2)] bg-[var(--surface2)]/50 p-2.5 rounded-xl border border-[var(--line)]/10">
                      {l.description}
                    </p>
                  </div>
                ) : null}

                {/* Location Specifics */}
                <div className="pt-2 border-t border-[var(--line)]/15">
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex items-center gap-1.5">
                      <MapPin size={13} className={hasLocation ? "text-[var(--gold)]" : "text-[var(--ink3)]"} />
                      <span className="text-[11.5px] font-bold text-[var(--ink)]">
                        {hasLocation ? "Physical Location Required" : "Global / Digital Work"}
                      </span>
                    </div>
                    {hasLocation && targetLat != null && targetLng != null && (
                      <a
                        href={`https://www.google.com/maps?q=${targetLat},${targetLng}`}
                        target="_blank"
                        rel="noreferrer"
                        className="inline-flex items-center gap-1 text-[10.5px] font-bold text-[var(--sky)] hover:underline"
                      >
                        <span>Open Maps</span>
                        <ExternalLink size={10} />
                      </a>
                    )}
                  </div>

                  {hasLocation ? (
                    <div className="mt-2 grid grid-cols-2 gap-2 text-[11px]">
                      <div className="p-2 rounded-xl bg-[var(--surface2)] border border-[var(--line)]/10">
                        <span className="caps text-[7.5px] text-[var(--ink3)] block">Target Coordinates</span>
                        <span className="font-mono text-[10px] font-bold text-[var(--ink)]">
                          {targetLat != null && targetLng != null ? `${Number(targetLat).toFixed(4)}, ${Number(targetLng).toFixed(4)}` : "Specified by sponsor"}
                        </span>
                      </div>
                      <div className="p-2 rounded-xl bg-[var(--surface2)] border border-[var(--line)]/10">
                        <span className="caps text-[7.5px] text-[var(--ink3)] block">Perimeter Fence</span>
                        <span className="font-semibold text-[var(--ink)]">{radiusM} meters radius</span>
                      </div>
                    </div>
                  ) : (
                    <p className="mt-1 text-[11px] text-[var(--ink3)]">
                      No physical presence restriction. Submissions can be performed remotely from anywhere.
                    </p>
                  )}
                </div>

                {/* Oracle Protocol Mechanics */}
                <div className="pt-2 border-t border-[var(--line)]/15">
                  <span className="caps text-[8px] text-[var(--ink3)] font-bold block mb-1">
                    Verification Oracle & Methodology:
                  </span>
                  <div className="p-2.5 rounded-xl bg-[var(--surface2)]/60 border border-[var(--line)]/15 space-y-1">
                    <p className="text-[11.5px] font-bold text-[var(--ink)] flex items-center gap-1.5">
                      <span className="w-2 h-2 rounded-full bg-[var(--gold)]" />
                      {meta.oracleName}
                    </p>
                    <p className="text-[11px] leading-relaxed text-[var(--ink2)]">{meta.howItVerifies}</p>
                  </div>
                </div>

                {/* Capacity & Eligibility */}
                <div className="pt-2 border-t border-[var(--line)]/15 grid grid-cols-2 gap-2 text-[11px]">
                  <div className="p-2 rounded-xl bg-[var(--surface2)] border border-[var(--line)]/10">
                    <span className="caps text-[7.5px] text-[var(--ink3)] block">Participation Capacity</span>
                    <span className="font-semibold text-[var(--ink)]">
                      {meta.isBounty ? "Single Winner (First to complete)" : "1-on-1 Equipment Loan"}
                    </span>
                  </div>
                  <div className="p-2 rounded-xl bg-[var(--surface2)] border border-[var(--line)]/10">
                    <span className="caps text-[7.5px] text-[var(--ink3)] block">Minimum Trust</span>
                    <span className="font-semibold text-[var(--ink)]">
                      Trust ≥ {contract?.minTrust || 0} ({trustTier(contract?.minTrust || 0).name})
                    </span>
                  </div>
                </div>
              </div>

              {/* Protocol Notes Checklist */}
              {notes.length > 0 && (
                <div>
                  <p className="caps mb-2 text-[8px] text-[var(--ink3)] font-bold tracking-wider">Protocol Covenants</p>
                  <div className="rounded-2xl border border-[var(--line)]/20 bg-[var(--surface)] p-3.5">
                    <ul className="space-y-2">
                      {notes.map((n, i) => (
                        <li key={i} className="flex gap-2 text-[11.5px] leading-snug text-[var(--ink2)]">
                          <span className="mt-[5px] h-1 w-1 flex-none rotate-45 bg-[var(--gold)]" />
                          <span>{n}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}

              {/* Active Contract Position if viewer already accepted */}
              {data.viewer?.escrow && (
                <div className="space-y-2">
                  <p className="caps text-[8px] text-[var(--sky)] font-bold tracking-wider">Your Active Contract</p>
                  <ContractTimeline escrow={{ ...data.viewer.escrow, amountNIM: l.collateralNIM }} />
                </div>
              )}

              {/* Owner Controls View */}
              {data.viewer?.isOwner && (
                <div className="rounded-2xl border border-[var(--gold)]/35 bg-[var(--surface)] p-4 shadow-sm">
                  <div className="flex items-center justify-between">
                    <span className="caps text-[8.5px] font-bold text-[var(--gold)]">Listing Management</span>
                    <span className="text-[11px] font-mono text-[var(--ink3)]">
                      {data.viewer.activeParticipants} active lock(s)
                    </span>
                  </div>
                  <p className="text-[13px] font-bold text-[var(--ink)] mt-1">This is your listing.</p>
                  <OwnerControls
                    listingId={String(l.id)}
                    hasLocks={Number(data.viewer.activeParticipants) > 0}
                    activeCount={Number(data.viewer.activeParticipants)}
                    listingKind={l.kind}
                    amountNIM={l.collateralNIM}
                    listingTitle={l.title}
                    onDone={onClose}
                    onShowQr={onShowQr}
                  />
                </div>
              )}

              {/* Deep Collapsible Protocol Dossier */}
              <ProtocolDossier
                listing={l}
                contract={contract}
                meta={meta}
                isOwner={Boolean(data.viewer?.isOwner)}
              />

              {/* Report & Flagging */}
              <ReportControl listingId={String(l.id)} isOwner={Boolean(data.viewer?.isOwner)} />

              {/* Locked Out Alert */}
              {lockedOut && (
                <div className="flex items-start gap-2.5 rounded-2xl p-3.5 bg-[var(--wax-dim)] border border-[var(--wax)]/35 text-[var(--ink)]">
                  <ShieldAlert size={16} className="mt-0.5 flex-none text-[var(--wax)]" />
                  <p className="text-[12px] leading-snug">
                    This contract requires a trust score ≥ {contract!.minTrust}. Your current score is{" "}
                    {viewerTrust} ({trustTier(viewerTrust).name.toLowerCase()}). Complete a few verified acts on Acta to build reputation.
                  </p>
                </div>
              )}
            </>
          )}
        </div>

        {/* Sticky Action Footer */}
        {l && !data.viewer?.escrow && !data.viewer?.isOwner && (() => {
          const isRentReq = l.kind === "borrow" && l.borrowMode === "rent";
          return (
            <div className="border-t border-[var(--line)] p-4 bg-[var(--surface)] space-y-2">
              <p className="marginalia text-center text-[11px]">
                {meta.isBounty
                  ? `Reward: ${l.collateralNIM.toLocaleString()} NIM · 0 NIM to accept · ${contract?.deadlineHours ? `${contract.deadlineHours}h window` : "No expiry"} · Judged by ${meta.oracleName}`
                  : isRentReq
                  ? `Vault collateral: ${l.collateralNIM.toLocaleString()} NIM pre-locked by requester · 0 NIM to fulfill · ${l.durationDays || 1} day covenant`
                  : `Locks ${l.collateralNIM.toLocaleString()} NIM · 100% refundable · ${l.durationDays || 1} day covenant · Judged by mutual return scan`}
              </p>

              <button
                disabled={lockedOut}
                onClick={() => {
                  onAccept(l);
                  onClose();
                }}
                className={`press flex w-full items-center justify-center gap-2 rounded-xl py-3.5 text-[14px] font-bold shadow-md transition-all ${
                  meta.isBounty
                    ? "bg-gradient-to-r from-[var(--gold)] to-[var(--gold2)] text-[#181206]"
                    : "bg-gradient-to-r from-[var(--sky)] to-[color-mix(in_srgb,var(--sky)_80%,#1e3a8a)] text-white"
                }`}
              >
                {meta.isBounty ? (
                  <>
                    <Zap size={15} className="fill-current" />
                    <span>Accept Bounty Challenge</span>
                    <ArrowRight size={14} />
                  </>
                ) : isRentReq ? (
                  <>
                    <Lock size={15} />
                    <span>Accept & Fulfill Rental Request</span>
                    <ArrowRight size={14} />
                  </>
                ) : (
                  <>
                    <Lock size={15} />
                    <span>Review & Lock Collateral ({l.collateralNIM.toLocaleString()} NIM)</span>
                    <ArrowRight size={14} />
                  </>
                )}
              </button>

              <p className="marginalia text-center text-[10.5px]">
                {meta.isBounty
                  ? "Free to accept. No collateral or payment required. Funds are pre-locked in the protocol vault."
                  : isRentReq
                  ? "Free to accept. Requester's collateral is already vaulted. Mutual Return QR scan settles exchange."
                  : "Collateral moves to the autonomous smart contract vault, not to the lender."}
              </p>
            </div>
          );
        })()}
      </div>
    </div>
  );
}
